language: generic
sudo : required 
services:
  - docker


before_install:
  - docker build -t vaibhavsharma199904/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vaibhavsharma199904/docker-react npm run test
