sudo : required 
services:
  - docker


before_install:
  - docker build -t vaibhavsharma199904/docker-react -f Dockerfile.dev .

script:
  - docker run vaibhavsharma199904/docker-react npm run test -- -- coverage
  